version: '3'

services:
  backend: # BackEnd GolangでAPIを受け取って処理
    container_name: "golang_container"
    build: 
      context: "./backend"
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend/:/go/src/app
    working_dir: "/go/src/app"
    networks:
      - app-tier
      - database-tier
    ports:
      - 8080:8080
    command: go run "./main.go"

  frontend: # FrontEnd Reactでガワを作成
    container_name: "react_container"
    build: 
      context: "./frontend"
      dockerfile: Dockerfile
    working_dir: "/usr/src/app"
    tty: true
    depends_on:
      - backend
    networks:
      - app-tier
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    command: "npm start"
  
  nginx: #プロキシサーバーとして利用
    container_name: nginx_container
    image: nginx:perl
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/.:/etc/nginx/
    depends_on:
      - mysql
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
  database-tier:
    driver: bridge