DROP DATABASE IF EXISTS react_go_app;
CREATE DATABASE react_go_app;
USE react_go_app;
DROP TABLE IF EXISTS name;
 
CREATE TABLE name (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ItemName TEXT NOT NULL,
Price INT NOT NULL,
Stock INT NOT NULL
)
 
